### ISSUE TITLE
/tmp/docker.stock vs. /var/run/docker.stock in README

### ISSUE THREAD

**Issue by bikaro** [hardillb/traefik-avahi-helper#2]
Where the volumes are listed it says `/var/run/docker.sock:/tmp/docker.sock` while in the command below `/var/run/docker.sock:/var/run/docker.sock` is used. I guess second is right because the other does not work, so it should be a quick fix to make everybody happy again.

**Comment by hardillb** [comment]
closed by https://github.com/hardillb/traefik-avahi-helper/commit/c7dd2a483f70ce972bd8d2ac8b68e57490efe29a
