### ISSUE TITLE
Idea: hostnames discovery via traefik api

### ISSUE THREAD

**Issue by ReDetection** [hardillb/traefik-avahi-helper#6]
Thank you for the nice project! I use it just a couple of days but absolutely love it! 👍

One idea: some of my traefik services are not inside the docker container, but just a proxy to some different services. So this might be helpful to actually look for hostnames in traefik and publish it via mdns.

**Comment by hardillb** [comment]
If you want to contribute a PR to that effect fine, but this code was intended to run purely with Docker.
